#
# TODO:
# - Description
#

# Site settings
title: Data Driven Drawings
subtitle: An Approach to Autobiographical Animation
author: Juan Camilo González
email: info@juancgonzalez.com
description: PhD dissertation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dddrawings.com/" # the base hostname & protocol for your site
# Social Media Profiles
twitter_username: '@1cgonza'
github_username: 1cgonza
google_profile: https://plus.google.com/+JuanCamiloGonz%C3%A1lezJ/posts
# Default Images
image: https://farm9.staticflickr.com/8592/16218761572_6100bf03d9_o.jpg
thumb: https://farm9.staticflickr.com/8592/16218761572_016c2e0f3c.jpg
no_thumb: https://farm3.staticflickr.com/2950/15297536047_e9da6fd148.jpg
# Javascipt Libraries URL
libraries:
  jquery: //ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
  jqueryui: //ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js
  d3: https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js